using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace GameFramework.LocalizationData.Editor
{
    /// <summary>
    /// 生成所有语言资产共用的数据包、分表结构和语言目录类型。
    /// </summary>
    internal static class LocalizationDataCodeGenerator
    {
        private const string GeneratedMarker = "// <auto-generated by GameFramework.LocalizationDataCreator>";

        public static bool Generate(string scriptAssetFolder, string previousScriptAssetFolder, IReadOnlyList<string> languages, out string generatedAssetPath)
        {
            if (languages == null)
            {
                throw new ArgumentNullException(nameof(languages));
            }
            if (languages.Count == 0)
            {
                throw new ArgumentException("至少需要一种语言才能生成语言枚举。", nameof(languages));
            }

            string normalizedFolder = NormalizeAssetFolderPath(scriptAssetFolder, nameof(scriptAssetFolder));
            string normalizedPreviousFolder = NormalizeOptionalAssetFolderPath(previousScriptAssetFolder);
            generatedAssetPath = normalizedFolder + "/" + LocalizationGenerationPaths.GeneratedFileName;
            string generatedCatalogAssetPath = normalizedFolder + "/" + LocalizationGenerationPaths.GeneratedCatalogFileName;
            string generatedLanguageAssetPath = normalizedFolder + "/" + LocalizationGenerationPaths.GeneratedLanguageFileName;

            if (!string.IsNullOrEmpty(normalizedPreviousFolder) && !string.Equals(normalizedPreviousFolder, normalizedFolder, StringComparison.OrdinalIgnoreCase))
            {
                MovePreviousGeneratedFile(normalizedPreviousFolder + "/" + LocalizationGenerationPaths.GeneratedFileName, generatedAssetPath);
                MovePreviousGeneratedFile(normalizedPreviousFolder + "/" + LocalizationGenerationPaths.GeneratedCatalogFileName, generatedCatalogAssetPath);
                MovePreviousGeneratedFile(normalizedPreviousFolder + "/" + LocalizationGenerationPaths.GeneratedLanguageFileName, generatedLanguageAssetPath);
            }

            string outputPath = GetAbsoluteProjectPath(generatedAssetPath);
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? throw new InvalidOperationException($"无法确定脚本输出目录：{outputPath}"));
            bool dataScriptChanged = WriteGeneratedFile(outputPath, BuildDataSource());
            bool catalogScriptChanged = WriteGeneratedFile(GetAbsoluteProjectPath(generatedCatalogAssetPath), BuildCatalogSource());
            bool languageScriptChanged = WriteGeneratedFile(GetAbsoluteProjectPath(generatedLanguageAssetPath), BuildLanguageSource(languages));
            return dataScriptChanged || catalogScriptChanged || languageScriptChanged;
        }

        private static string BuildDataSource()
        {
            StringBuilder source = new();
            source.AppendLine(GeneratedMarker);
            source.AppendLine("// 此文件由本地化配置表工具生成，请勿手动修改。");
            source.AppendLine("// </auto-generated>");
            source.AppendLine();
            source.AppendLine("using System;");
            source.AppendLine("using System.Collections.Generic;");
            source.AppendLine("using UnityEngine;");
            source.AppendLine();
            source.AppendLine($"namespace {LocalizationGenerationPaths.GeneratedNamespace}");
            source.AppendLine("{");
            source.AppendLine("    [Serializable]");
            source.AppendLine($"    public sealed class {LocalizationGenerationPaths.GeneratedEntryTypeName}");
            source.AppendLine("    {");
            source.AppendLine("        [SerializeField] private string key = string.Empty;");
            source.AppendLine("        [SerializeField] private string value = string.Empty;");
            source.AppendLine();
            source.AppendLine("        public string Key => key;");
            source.AppendLine("        public string Value => value;");
            source.AppendLine("    }");
            source.AppendLine();
            source.AppendLine("    [Serializable]");
            source.AppendLine($"    public sealed class {LocalizationGenerationPaths.GeneratedSectionTypeName}");
            source.AppendLine("    {");
            source.AppendLine("        [SerializeField] private string tableId = string.Empty;");
            source.AppendLine($"        [SerializeField] private List<{LocalizationGenerationPaths.GeneratedEntryTypeName}> entries = new();");
            source.AppendLine();
            source.AppendLine("        public string TableId => tableId;");
            source.AppendLine($"        public IReadOnlyList<{LocalizationGenerationPaths.GeneratedEntryTypeName}> Entries => entries;");
            source.AppendLine("        public int Count => entries.Count;");
            source.AppendLine("    }");
            source.AppendLine();
            source.AppendLine($"    public sealed class {LocalizationGenerationPaths.GeneratedTypeName} : ScriptableObject");
            source.AppendLine("    {");
            source.AppendLine($"        [SerializeField, HideInInspector] private string generatorId = \"{LocalizationGenerationPaths.GeneratorId}\";");
            source.AppendLine("        [SerializeField] private string language = string.Empty;");
            source.AppendLine($"        [SerializeField] private List<{LocalizationGenerationPaths.GeneratedSectionTypeName}> sections = new();");
            source.AppendLine();
            source.AppendLine("        internal string GeneratorId => generatorId;");
            source.AppendLine("        public string Language => language;");
            source.AppendLine($"        public IReadOnlyList<{LocalizationGenerationPaths.GeneratedSectionTypeName}> Sections => sections;");
            source.AppendLine("        public int SectionCount => sections.Count;");
            source.AppendLine("    }");
            source.AppendLine();
            source.AppendLine("    [Serializable]");
            source.AppendLine($"    public sealed class {LocalizationGenerationPaths.GeneratedPackageReferenceTypeName}");
            source.AppendLine("    {");
            source.AppendLine("        [SerializeField] private string language = string.Empty;");
            source.AppendLine("        [SerializeField] private string resourcesPath = string.Empty;");
            source.AppendLine();
            source.AppendLine("        public string Language => language;");
            source.AppendLine("        public string ResourcesPath => resourcesPath;");
            source.AppendLine("    }");
            source.AppendLine("}");
            return source.ToString();
        }

        private static string BuildCatalogSource()
        {
            StringBuilder source = new();
            source.AppendLine(GeneratedMarker);
            source.AppendLine("// 此文件由本地化配置表工具生成，请勿手动修改。");
            source.AppendLine("// </auto-generated>");
            source.AppendLine();
            source.AppendLine("using System.Collections.Generic;");
            source.AppendLine("using UnityEngine;");
            source.AppendLine();
            source.AppendLine($"namespace {LocalizationGenerationPaths.GeneratedNamespace}");
            source.AppendLine("{");
            source.AppendLine($"    public sealed class {LocalizationGenerationPaths.GeneratedCatalogTypeName} : ScriptableObject");
            source.AppendLine("    {");
            source.AppendLine($"        [SerializeField, HideInInspector] private string generatorId = \"{LocalizationGenerationPaths.GeneratorId}\";");
            source.AppendLine("        [SerializeField] private string defaultLanguage = string.Empty;");
            source.AppendLine($"        [SerializeField] private List<{LocalizationGenerationPaths.GeneratedPackageReferenceTypeName}> packages = new();");
            source.AppendLine();
            source.AppendLine("        internal string GeneratorId => generatorId;");
            source.AppendLine("        public string DefaultLanguage => defaultLanguage;");
            source.AppendLine($"        public IReadOnlyList<{LocalizationGenerationPaths.GeneratedPackageReferenceTypeName}> Packages => packages;");
            source.AppendLine("        public int Count => packages.Count;");
            source.AppendLine("    }");
            source.AppendLine("}");
            return source.ToString();
        }

        private static string BuildLanguageSource(IReadOnlyList<string> languages)
        {
            StringBuilder source = new();
            source.AppendLine(GeneratedMarker);
            source.AppendLine("// 此文件由本地化配置表工具生成，请勿手动修改。");
            source.AppendLine("// SO、Catalog 和 PlayerPrefs 应继续保存字符串语言 ID，不应序列化此枚举的数值。");
            source.AppendLine("// </auto-generated>");
            source.AppendLine();
            source.AppendLine("using System;");
            source.AppendLine();
            source.AppendLine($"namespace {LocalizationGenerationPaths.GeneratedNamespace}");
            source.AppendLine("{");
            source.AppendLine($"    public enum {LocalizationGenerationPaths.GeneratedLanguageTypeName}");
            source.AppendLine("    {");
            for (int index = 0; index < languages.Count; index++)
            {
                source.AppendLine($"        {languages[index]}{(index < languages.Count - 1 ? "," : string.Empty)}");
            }
            source.AppendLine("    }");
            source.AppendLine();
            source.AppendLine("    public static class LocalizationLanguageUtility");
            source.AppendLine("    {");
            source.AppendLine($"        public static string ToLanguageId(this {LocalizationGenerationPaths.GeneratedLanguageTypeName} language)");
            source.AppendLine("        {");
            source.AppendLine("            return language switch");
            source.AppendLine("            {");
            foreach (string language in languages)
            {
                source.AppendLine($"                {LocalizationGenerationPaths.GeneratedLanguageTypeName}.{language} => \"{language}\",");
            }
            source.AppendLine("                _ => throw new ArgumentOutOfRangeException(nameof(language), language, \"未知的本地化语言枚举值。\")");
            source.AppendLine("            };");
            source.AppendLine("        }");
            source.AppendLine();
            source.AppendLine($"        public static bool TryParseLanguage(string languageId, out {LocalizationGenerationPaths.GeneratedLanguageTypeName} language)");
            source.AppendLine("        {");
            source.AppendLine("            switch (languageId)");
            source.AppendLine("            {");
            foreach (string language in languages)
            {
                source.AppendLine($"                case \"{language}\":");
                source.AppendLine($"                    language = {LocalizationGenerationPaths.GeneratedLanguageTypeName}.{language};");
                source.AppendLine("                    return true;");
            }
            source.AppendLine("                default:");
            source.AppendLine("                    language = default;");
            source.AppendLine("                    return false;");
            source.AppendLine("            }");
            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            return source.ToString();
        }

        private static bool WriteGeneratedFile(string outputPath, string source)
        {
            EnsureOwnedFileIfExists(outputPath);
            if (File.Exists(outputPath) && string.Equals(File.ReadAllText(outputPath, Encoding.UTF8), source, StringComparison.Ordinal))
            {
                return false;
            }

            File.WriteAllText(outputPath, source, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            return true;
        }

        private static void MovePreviousGeneratedFile(string previousAssetPath, string targetAssetPath)
        {
            string previousPath = GetAbsoluteProjectPath(previousAssetPath);
            if (!File.Exists(previousPath))
            {
                return;
            }

            EnsureOwnedFileIfExists(previousPath);
            string targetPath = GetAbsoluteProjectPath(targetAssetPath);
            if (File.Exists(targetPath))
            {
                EnsureOwnedFileIfExists(targetPath);
                AssetDatabase.DeleteAsset(previousAssetPath);
                return;
            }

            string error = AssetDatabase.MoveAsset(previousAssetPath, targetAssetPath);
            if (!string.IsNullOrEmpty(error))
            {
                throw new IOException($"移动本地化 SO 类型脚本失败：{error}");
            }
        }

        private static void EnsureOwnedFileIfExists(string path)
        {
            if (!File.Exists(path))
            {
                return;
            }

            using StreamReader reader = new(path, Encoding.UTF8, detectEncodingFromByteOrderMarks: true);
            string firstLine = reader.ReadLine();
            if (!string.Equals(firstLine, GeneratedMarker, StringComparison.Ordinal))
            {
                throw new InvalidOperationException($"目标脚本不是本地化配置表工具生成的文件，拒绝覆盖：{path}");
            }
        }

        private static string NormalizeAssetFolderPath(string path, string parameterName)
        {
            if (string.IsNullOrWhiteSpace(path))
            {
                throw new ArgumentException("脚本输出目录不能为空。", parameterName);
            }

            string normalized = path.Replace('\\', '/').TrimEnd('/');
            if (normalized != "Assets" && !normalized.StartsWith("Assets/", StringComparison.Ordinal))
            {
                throw new ArgumentException($"脚本输出目录必须位于 Assets 下：{path}", parameterName);
            }

            return normalized;
        }

        private static string NormalizeOptionalAssetFolderPath(string path)
        {
            return string.IsNullOrWhiteSpace(path) ? null : NormalizeAssetFolderPath(path, nameof(path));
        }

        private static string GetAbsoluteProjectPath(string assetPath)
        {
            string projectRoot = Path.GetFullPath(Path.Combine(Application.dataPath, ".."));
            return Path.GetFullPath(Path.Combine(projectRoot, assetPath));
        }
    }
}
