// <auto-generated by GameFramework.LocalizationDataCreator>
// 此文件由本地化配置表工具生成，请勿手动修改。
// </auto-generated>

using System.Collections.Generic;
using UnityEngine;

namespace GameFramework.LocalizationSystem.Generated
{
    public sealed class LocalizationCatalogSO : ScriptableObject
    {
        [SerializeField, HideInInspector] private string generatorId = "GameFramework.LocalizationDataCreator";
        [SerializeField] private string defaultLanguage = string.Empty;
        [SerializeField] private List<LocalizationPackageReference> packages = new();

        internal string GeneratorId => generatorId;
        public string DefaultLanguage => defaultLanguage;
        public IReadOnlyList<LocalizationPackageReference> Packages => packages;
        public int Count => packages.Count;
    }
}
