// <auto-generated by GameFramework.LocalizationDataCreator>
// 此文件由本地化配置表工具生成，请勿手动修改。
// </auto-generated>

using System;
using System.Collections.Generic;
using UnityEngine;

namespace GameFramework.LocalizationSystem.Generated
{
    [Serializable]
    public sealed class LocalizationDataEntry
    {
        [SerializeField] private string key = string.Empty;
        [SerializeField] private string value = string.Empty;

        public string Key => key;
        public string Value => value;
    }

    [Serializable]
    public sealed class LocalizationTableSection
    {
        [SerializeField] private string tableId = string.Empty;
        [SerializeField] private List<LocalizationDataEntry> entries = new();

        public string TableId => tableId;
        public IReadOnlyList<LocalizationDataEntry> Entries => entries;
        public int Count => entries.Count;
    }

    public sealed class LocalizationDataSO : ScriptableObject
    {
        [SerializeField, HideInInspector] private string generatorId = "GameFramework.LocalizationDataCreator";
        [SerializeField] private string language = string.Empty;
        [SerializeField] private List<LocalizationTableSection> sections = new();

        internal string GeneratorId => generatorId;
        public string Language => language;
        public IReadOnlyList<LocalizationTableSection> Sections => sections;
        public int SectionCount => sections.Count;
    }

    [Serializable]
    public sealed class LocalizationPackageReference
    {
        [SerializeField] private string language = string.Empty;
        [SerializeField] private string resourcesPath = string.Empty;

        public string Language => language;
        public string ResourcesPath => resourcesPath;
    }
}
