// <auto-generated by GameFramework.LocalizationDataCreator>
// 此文件由本地化配置表工具生成，请勿手动修改。
// SO、Catalog 和 PlayerPrefs 应继续保存字符串语言 ID，不应序列化此枚举的数值。
// </auto-generated>

using System;

namespace GameFramework.LocalizationSystem.Generated
{
    public enum LocalizationLanguage
    {
        ChineseSimplified,
        ChineseTraditional,
        English
    }

    public static class LocalizationLanguageUtility
    {
        public static string ToLanguageId(this LocalizationLanguage language)
        {
            return language switch
            {
                LocalizationLanguage.ChineseSimplified => "ChineseSimplified",
                LocalizationLanguage.ChineseTraditional => "ChineseTraditional",
                LocalizationLanguage.English => "English",
                _ => throw new ArgumentOutOfRangeException(nameof(language), language, "未知的本地化语言枚举值。")
            };
        }

        public static bool TryParseLanguage(string languageId, out LocalizationLanguage language)
        {
            switch (languageId)
            {
                case "ChineseSimplified":
                    language = LocalizationLanguage.ChineseSimplified;
                    return true;
                case "ChineseTraditional":
                    language = LocalizationLanguage.ChineseTraditional;
                    return true;
                case "English":
                    language = LocalizationLanguage.English;
                    return true;
                default:
                    language = default;
                    return false;
            }
        }
    }
}
