using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;
using Object = UnityEngine.Object;

namespace GameFramework.UI.Editor
{
    internal static class UIElementCodeGenerator
    {
        private const string GeneratedFileMarker = "// <auto-generated by UIElementBuilder>";

        public static List<string> Validate(UIElementBuilder builder)
        {
            List<string> errors = new();
            if (builder == null)
            {
                errors.Add("UIElementBuilder 不存在。");
                return errors;
            }

            HashSet<string> fieldNames = new(StringComparer.Ordinal);
            HashSet<string> clickHandlerNames = new(StringComparer.Ordinal);
            for (int i = 0; i < builder.Bindings.Count; i++)
            {
                UIElementBinding binding = builder.Bindings[i];
                if (binding == null)
                {
                    errors.Add($"第 {i} 条绑定为空。");
                    continue;
                }

                if (!CSharpIdentifierUtility.IsValid(binding.FieldName)) errors.Add($"第 {i} 条绑定的字段名“{binding.FieldName}”不是有效的 C# 标识符。");
                else if (!fieldNames.Add(binding.FieldName)) errors.Add($"字段名“{binding.FieldName}”重复。");

                Object target = binding.Target;
                if (target == null)
                {
                    errors.Add($"绑定“{binding.FieldName}”没有目标对象。");
                    continue;
                }

                if (target is not GameObject && target is not Component)
                {
                    errors.Add($"绑定“{binding.FieldName}”只能引用 GameObject 或 Component。");
                    continue;
                }

                Transform targetTransform = target is GameObject gameObject ? gameObject.transform : ((Component)target).transform;
                if (!targetTransform.IsChildOf(builder.transform)) errors.Add($"绑定“{binding.FieldName}”不属于 {builder.name} 的层级。");
                if (binding.GenerateClickHandler && target is not Button) errors.Add($"绑定“{binding.FieldName}”只有引用 Button 时才能生成点击方法。");
                if (binding.GenerateClickHandler && !clickHandlerNames.Add(GetClickHandlerName(binding.FieldName))) errors.Add($"绑定“{binding.FieldName}”生成的点击方法名称重复。");
            }

            ValidatePanel(builder, errors);
            return errors;
        }

        public static string GenerateBindingFile(UIElementBuilder builder)
        {
            List<string> errors = Validate(builder);
            if (errors.Count > 0) throw new InvalidOperationException(string.Join(Environment.NewLine, errors));

            BasePanel panel = builder.GetComponent<BasePanel>();
            MonoScript panelScript = MonoScript.FromMonoBehaviour(panel);
            string panelAssetPath = AssetDatabase.GetAssetPath(panelScript);
            string directory = Path.GetDirectoryName(panelAssetPath)?.Replace('\\', '/');
            if (string.IsNullOrWhiteSpace(directory)) throw new InvalidOperationException($"无法确定面板脚本“{panel.GetType().Name}”所在目录。");

            string bindingAssetPath = $"{directory}/{panel.GetType().Name}.Binding.cs";
            string absolutePath = Path.GetFullPath(bindingAssetPath);
            if (File.Exists(absolutePath))
            {
                string existingCode = File.ReadAllText(absolutePath);
                if (!existingCode.StartsWith(GeneratedFileMarker, StringComparison.Ordinal)) throw new InvalidOperationException($"目标文件“{bindingAssetPath}”不是 UIElementBuilder 生成的文件，已拒绝覆盖。");
            }

            string generatedCode = Generate(builder, panel.GetType());
            File.WriteAllText(absolutePath, generatedCode, new UTF8Encoding(false));
            AssetDatabase.ImportAsset(bindingAssetPath, ImportAssetOptions.ForceUpdate);
            return bindingAssetPath;
        }

        public static int GetClickCallbackCount(UIElementBuilder builder)
        {
            if (builder == null) return 0;

            int count = 0;
            for (int i = 0; i < builder.Bindings.Count; i++)
            {
                UIElementBinding binding = builder.Bindings[i];
                if (binding != null && binding.GenerateClickHandler && binding.Target is Button) count++;
            }

            return count;
        }

        public static string GenerateClickCallbackTemplate(UIElementBuilder builder)
        {
            List<string> errors = Validate(builder);
            if (errors.Count > 0) throw new InvalidOperationException(string.Join(Environment.NewLine, errors));
            if (GetClickCallbackCount(builder) == 0) throw new InvalidOperationException("当前没有启用点击方法的 Button 绑定。");

            StringBuilder code = new();
            code.AppendLine("#region 点击回调");
            for (int i = 0; i < builder.Bindings.Count; i++)
            {
                UIElementBinding binding = builder.Bindings[i];
                if (!binding.GenerateClickHandler) continue;
                code.AppendLine();
                code.AppendLine($"partial void {GetClickHandlerName(binding.FieldName)}()");
                code.AppendLine("{");
                code.AppendLine("}");
            }

            code.AppendLine();
            code.Append("#endregion");
            return code.ToString();
        }

        private static string Generate(UIElementBuilder builder, Type panelType)
        {
            string namespaceName = panelType.Namespace;
            bool hasNamespace = !string.IsNullOrWhiteSpace(namespaceName);
            string typeIndent = hasNamespace ? "    " : string.Empty;
            string memberIndent = $"{typeIndent}    ";
            string bodyIndent = $"{memberIndent}    ";
            string accessibility = panelType.IsPublic ? "public" : "internal";
            StringBuilder code = new();

            code.AppendLine(GeneratedFileMarker);
            code.AppendLine("// 此文件由 UIElementBuilder 自动生成，手动修改会在下次生成时丢失。");
            code.AppendLine();
            if (hasNamespace)
            {
                code.AppendLine($"namespace {namespaceName}");
                code.AppendLine("{");
            }

            code.AppendLine($"{typeIndent}{accessibility} partial class {panelType.Name}");
            code.AppendLine($"{typeIndent}{{");
            code.AppendLine($"{memberIndent}#region UI Bindings");
            code.AppendLine();
            for (int i = 0; i < builder.Bindings.Count; i++)
            {
                UIElementBinding binding = builder.Bindings[i];
                code.AppendLine($"{memberIndent}private {GetTypeName(binding.Target)} {binding.FieldName};");
            }

            code.AppendLine();
            code.AppendLine($"{memberIndent}protected override void OnBindUI()");
            code.AppendLine($"{memberIndent}{{");
            code.AppendLine($"{bodyIndent}base.OnBindUI();");
            if (builder.BindingCount > 0) code.AppendLine($"{bodyIndent}global::GameFramework.UI.UIElementBuilder builder = GetComponent<global::GameFramework.UI.UIElementBuilder>();");
            for (int i = 0; i < builder.Bindings.Count; i++)
            {
                UIElementBinding binding = builder.Bindings[i];
                code.AppendLine($"{bodyIndent}{binding.FieldName} = builder.Get<{GetTypeName(binding.Target)}>(nameof({binding.FieldName}));");
            }

            for (int i = 0; i < builder.Bindings.Count; i++)
            {
                UIElementBinding binding = builder.Bindings[i];
                if (binding.GenerateClickHandler) code.AppendLine($"{bodyIndent}{binding.FieldName}.onClick.AddListener(Handle{GetClickHandlerName(binding.FieldName)});");
            }

            code.AppendLine($"{memberIndent}}}");
            for (int i = 0; i < builder.Bindings.Count; i++)
            {
                UIElementBinding binding = builder.Bindings[i];
                if (!binding.GenerateClickHandler) continue;
                string handlerName = GetClickHandlerName(binding.FieldName);
                code.AppendLine();
                code.AppendLine($"{memberIndent}private void Handle{handlerName}()");
                code.AppendLine($"{memberIndent}{{");
                code.AppendLine($"{bodyIndent}{handlerName}();");
                code.AppendLine($"{memberIndent}}}");
                code.AppendLine();
                code.AppendLine($"{memberIndent}partial void {handlerName}();");
            }

            code.AppendLine();
            code.AppendLine($"{memberIndent}#endregion");
            code.AppendLine($"{typeIndent}}}");
            if (hasNamespace) code.AppendLine("}");
            return code.ToString();
        }

        private static void ValidatePanel(UIElementBuilder builder, ICollection<string> errors)
        {
            BasePanel[] panels = builder.GetComponents<BasePanel>();
            if (panels.Length != 1)
            {
                errors.Add(panels.Length == 0 ? "UIElementBuilder 所在对象必须挂载一个 BasePanel 派生组件。" : "UIElementBuilder 所在对象只能挂载一个 BasePanel 派生组件。");
                return;
            }

            Type panelType = panels[0].GetType();
            if (panelType.IsNested) errors.Add($"面板类型“{panelType.FullName}”不能是嵌套类型。");
            if (panelType.IsGenericType) errors.Add($"面板类型“{panelType.FullName}”不能是泛型类型。");

            MonoScript panelScript = MonoScript.FromMonoBehaviour(panels[0]);
            if (panelScript == null)
            {
                errors.Add($"无法定位面板类型“{panelType.FullName}”的 MonoScript。");
                return;
            }

            string panelAssetPath = AssetDatabase.GetAssetPath(panelScript);
            if (!panelAssetPath.StartsWith("Assets/", StringComparison.Ordinal)) errors.Add($"面板脚本必须位于 Assets 目录，当前路径为“{panelAssetPath}”。");
            if (!IsPartialClass(panelScript.text, panelType.Name)) errors.Add($"面板类“{panelType.Name}”必须声明为 partial，例如：public partial class {panelType.Name} : BasePanel");
        }

        private static bool IsPartialClass(string sourceCode, string typeName)
        {
            return Regex.IsMatch(sourceCode, $@"\bpartial\s+class\s+{Regex.Escape(typeName)}\b");
        }

        private static string GetClickHandlerName(string fieldName)
        {
            return $"On{CSharpIdentifierUtility.ToPascalCase(fieldName)}Click";
        }

        private static string GetTypeName(Object target)
        {
            Type type = target is GameObject ? typeof(GameObject) : target.GetType();
            string fullName = type.FullName ?? type.Name;
            return $"global::{fullName.Replace('+', '.')}";
        }
    }
}
