// <auto-generated>
// 此文件由配置表工具生成，请勿手动修改。
// </auto-generated>

using GameFramework.ConfigSystem;

namespace GameFramework.ConfigData.Generated
{
    /// <summary>
    /// TestTweData 配置表资产类型。
    /// </summary>
    public sealed class TestTweDataSO : ConfigTableSO<TestTweData>
    {
    }
}
