// <auto-generated>
// 此文件由配置表工具生成，请勿手动修改。
// </auto-generated>

using System;
using System.Collections.Generic;
using UnityEngine;
using GameFramework.ConfigSystem;

namespace GameFramework.ConfigData.Generated
{
    [Serializable]
    public sealed class TestOneData : ConfigDataRowBase
    {
        [SerializeField]
        private int id;

        /// <summary>
        /// Id导出测试
        /// </summary>
        public override int ID
        {
            get => id;
            set => id = value;
        }

        /// <summary>
        /// 字符串导出测试
        /// </summary>
        public string TestString = string.Empty;

        /// <summary>
        /// 浮点数导出测试
        /// </summary>
        public float TestFloat;

        /// <summary>
        /// 布尔值导出测试
        /// </summary>
        public bool TestBool;

        /// <summary>
        /// 英文逗号分隔测试
        /// </summary>
        public string TestComma = string.Empty;
    }
}
