// <auto-generated>
// 此文件由配置表工具生成，请勿手动修改。
// </auto-generated>

using System;
using System.Collections.Generic;
using UnityEngine;
using GameFramework.ConfigSystem;

namespace GameFramework.ConfigData.Generated
{
    [Serializable]
    public sealed class TestTweData : ConfigDataBase
    {
        [SerializeField]
        private int id;

        /// <summary>
        /// Id导出测试
        /// </summary>
        public override int ID
        {
            get => id;
            set => id = value;
        }

        /// <summary>
        /// 整数列表导出测试
        /// </summary>
        public List<int> TestIntList = new List<int>();

        /// <summary>
        /// 浮点数列表导出测试
        /// </summary>
        public List<float> TestFloatList = new List<float>();

        /// <summary>
        /// 布尔值列表导出测试
        /// </summary>
        public List<bool> TestBoolList = new List<bool>();

        /// <summary>
        /// 字符串列表导出测试
        /// </summary>
        public List<string> TestStringlList = new List<string>();
    }
}
