// <auto-generated by UIElementBuilder>
// 此文件由 UIElementBuilder 自动生成，手动修改会在下次生成时丢失。

using GameFramework.UI;
using GameFramework.UI.Virtualization;

public partial class UITestPanel : BasePanel
{
    #region UI Bindings

    private LoopScrollViewVertical scrollView;

    protected override void OnBindUI()
    {
        base.OnBindUI();
        global::GameFramework.UI.UIElementBuilder builder = GetComponent<global::GameFramework.UI.UIElementBuilder>();
        scrollView = builder.Get<global::GameFramework.UI.Virtualization.LoopScrollViewVertical>(nameof(scrollView));
    }

    #endregion
}
